services:
  mysql:
    image: mysql:9.1.0
    restart: always
    volumes:
      - ./Database/Database.sql:/docker-entrypoint-initdb.d/Database.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "PTREDDIT"
  web:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - mysql
  server:
    build: ./server
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - web
